Update to support custom encodings
pveyes/raw.macro pull request #59
Opened 2022-06-24 07:24 UTC by cnnranderson

2022-06-25 06:44 UTC, pveyes requested changes
Please revert other files unrelated to the changes (package.json, package-lock, yarn.lock). Other than that it's great

Thanks for making this PR!

2022-06-25 06:44 UTC, pveyes commented on package.json
> +  "version": "0.5.0",
I'll cut another version manually by myself

2022-06-25 06:44 UTC, pveyes commented on raw.macro.d.ts
> +  export default function raw(rawPath: string, encoding?: string): string;
nice

2022-06-25 06:44 UTC, pveyes commented on src/__tests__/macro.test.js
> +    "set encoding": `
maybe "custom encoding" is more apt?

2022-06-25 07:15 UTC, cnnranderson commented on package.json
> +  "version": "0.5.0",
Fixed!

2022-06-25 07:15 UTC, cnnranderson commented on src/__tests__/macro.test.js
> +    "set encoding": `
Agreed. Updated

2022-06-27 06:50 UTC, pveyes approved these changes
LGTM

2022-06-27 06:52 UTC, merged